name: Deploy to SFTP with Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP with password
        uses: sand4rt/ftp-deployer@v1.4
        with:
          sftp: true                         # используем SFTP
          host: ${{ secrets.SFTP_HOST }}    # адрес сервера
          port: 22                          # порт SFTP
          username: ${{ secrets.SFTP_USERNAME }}  # логин
          password: ${{ secrets.SFTP_PASSWORD }}  # пароль
          remote_folder: /home/oknobalkon/public_html/  # целевая папка, обязательно с '/'
          local_folder: '.'                  # локальная папка - корень репозитория
          cleanup: false                    # не удалять файлы на сервере
          include: '["*"]'
          exclude: '["video-result/**","video-reviews/**"]'
          passive: true                    # пассивный режим (зависит от сервера)
          retries: 3   # количество повторов при неудаче
          retry-delay: 30  # время паузы между попытками, сек
